/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.net.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Luano Zubém
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    static Socket socketClient;
    
    //fluxos
    static DataInputStream fluxoDeEntrada;
    static DataOutputStream fluxoDeSaida;
    
    //Emojis
    String smile = "☺";
    String heart = "♥";
    
    //tempo
    static Date tempo = new Date();
    static SimpleDateFormat formatarHora = new SimpleDateFormat("hh:mm:ss");
    static String horaFormatada;
    
    //Oque vai ser enviado e o que vai ser recebido :|
    static String msgAserRecebida, msgAserEnviada;
    
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emoji_smile = new javax.swing.JLabel();
        emoji_heart = new javax.swing.JLabel();
        btn_alert = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        exibirMsg = new javax.swing.JTextArea();
        insiraTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("client_application");
        setAutoRequestFocus(false);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/bate-papo.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Emojis");

        emoji_smile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sorrir.png"))); // NOI18N
        emoji_smile.setToolTipText("Caso não queira pressionar este emoji, digite :) para obter resultado equivalente.");
        emoji_smile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emoji_smile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emoji_smileMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emoji_smileMouseExited(evt);
            }
        });

        emoji_heart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/heart.png"))); // NOI18N
        emoji_heart.setToolTipText("Caso não queira pressionar este emoji, digite <3 para obter resultado equivalente.");
        emoji_heart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emoji_heart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emoji_heartMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emoji_heartMouseExited(evt);
            }
        });

        btn_alert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mao.png"))); // NOI18N
        btn_alert.setToolTipText("Chama a atenção do servidor.");
        btn_alert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_alert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_alertMouseClicked(evt);
            }
        });

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/enviar-mensagem.png"))); // NOI18N
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });

        exibirMsg.setEditable(false);
        exibirMsg.setBackground(new java.awt.Color(0, 102, 102));
        exibirMsg.setColumns(20);
        exibirMsg.setFont(exibirMsg.getFont().deriveFont(exibirMsg.getFont().getStyle() | java.awt.Font.BOLD, exibirMsg.getFont().getSize()+1));
        exibirMsg.setForeground(new java.awt.Color(0, 51, 51));
        exibirMsg.setLineWrap(true);
        exibirMsg.setRows(5);
        exibirMsg.setTabSize(2);
        exibirMsg.setText("Aguardando mensagens do servidor\n...\n");
        exibirMsg.setToolTipText("mensagens recebidas do servidor serão exibidas aqui");
        exibirMsg.setWrapStyleWord(true);
        exibirMsg.setBorder(null);
        jScrollPane2.setViewportView(exibirMsg);

        insiraTexto.setBackground(new java.awt.Color(0, 102, 102));
        insiraTexto.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        insiraTexto.setForeground(new java.awt.Color(0, 51, 51));
        insiraTexto.setText("Digite aqui");
        insiraTexto.setToolTipText("");
        insiraTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                insiraTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                insiraTextoFocusLost(evt);
            }
        });

        jLabel2.setText("Caso queira encerrar a comunicação digite: sair");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(insiraTexto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 243, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(btnEnviar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 55, Short.MAX_VALUE)
                        .add(btn_alert))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(emoji_smile)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(emoji_heart))
                            .add(jLabel2))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(btn_alert, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .add(btnEnviar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .add(insiraTexto))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(emoji_smile)
                    .add(emoji_heart))
                .add(22, 22, 22))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 392, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 307, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        //Bloco responsável pelo envio de dados ao servidor
        //tempo
        tempo = new Date();
        horaFormatada = formatarHora.format(tempo);
        msgAserEnviada = insiraTexto.getText();
        try {
            switch (msgAserEnviada) {
                case "sair":
                    //Alterando o background e o texto de alguns componentes
                    exibirMsg.setForeground(new java.awt.Color(0, 102, 102));
                    exibirMsg.setBackground(new java.awt.Color(0, 51, 51));
                    insiraTexto.setBackground(new java.awt.Color(0, 51, 51));
                    //Interrompimento da conexão
                    exibirMsg.setText("Você encerrou a conexão!");
                    fluxoDeSaida.writeUTF(msgAserEnviada);
                    socketClient.close();
                    fluxoDeEntrada.close();
                    fluxoDeSaida.close();
                    break;
                case ":)":
                    //Caso o emoji smile seja enviado via terminal
                    fluxoDeSaida.writeUTF("\n"+horaFormatada+"_ CLIENTE: "+smile);
                    exibirMsg.setText(exibirMsg.getText()+"\n"+horaFormatada+"_ EU: "+msgAserEnviada);
                    break;
                case "<3":
                    //Caso o emoji heart seja enviado via terminal
                    fluxoDeSaida.writeUTF("\n"+horaFormatada+"_ CLIENTE: "+heart);
                    exibirMsg.setText(exibirMsg.getText()+"\n"+horaFormatada+"_ EU: "+msgAserEnviada);
                    break;
                default:
                    fluxoDeSaida.writeUTF("\n"+horaFormatada+"_ CLIENTE: "+msgAserEnviada);
                    //Exibi oque foi enviado
                    exibirMsg.setText(exibirMsg.getText()+"\n"+horaFormatada+"_ EU: "+msgAserEnviada);
                    break;
            }
        } catch (IOException e) {
            System.out.println("Error em -----> "+e);
        }
    }//GEN-LAST:event_btnEnviarMouseClicked

    private void emoji_smileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_smileMouseClicked
        //Emoji smile
        //tempo
        tempo = new Date();
        horaFormatada = formatarHora.format(tempo);
        emoji_smile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sorrir_1.png")));
        try {
            fluxoDeSaida.writeUTF("\n"+horaFormatada+"_ CLIENTE: "+smile);
            exibirMsg.setText(exibirMsg.getText()+"\n"+horaFormatada+"_ EU: "+smile);
        } catch (IOException e) {
            System.out.println("Error em -----> "+e);
        }
    }//GEN-LAST:event_emoji_smileMouseClicked

    private void emoji_heartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_heartMouseClicked
        //Emoji heart
        //tempo
        tempo = new Date();
        horaFormatada = formatarHora.format(tempo);
        emoji_heart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/heart_1.png")));
        try {
            fluxoDeSaida.writeUTF("\n"+horaFormatada+"_ CLIENTE: "+heart);
            exibirMsg.setText(exibirMsg.getText()+"\n"+horaFormatada+"_ EU: "+heart);
        } catch (IOException e) {
            System.out.println("Error em -----> "+e);
        }
    }//GEN-LAST:event_emoji_heartMouseClicked

    private void btn_alertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alertMouseClicked
        //Bloco responsável pelo encaminhamento do alerta ao servidor
        try {
            fluxoDeSaida.writeUTF("alerta");
        } catch (IOException e) {
            System.out.println("Impossivel enviar alerta! Motivo ===> "+e);
        }
    }//GEN-LAST:event_btn_alertMouseClicked

    private void insiraTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_insiraTextoFocusLost
        //Insere um texto no campo ao se perder o foco.
        insiraTexto.setText("Digite aqui");
    }//GEN-LAST:event_insiraTextoFocusLost

    private void insiraTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_insiraTextoFocusGained
        //Insere um texto vazio no campo ao se ganhar foco.
        insiraTexto.setText("");
    }//GEN-LAST:event_insiraTextoFocusGained

    private void emoji_smileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_smileMouseExited
        emoji_smile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sorrir.png")));
    }//GEN-LAST:event_emoji_smileMouseExited

    private void emoji_heartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_heartMouseExited
        emoji_heart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/heart.png")));
    }//GEN-LAST:event_emoji_heartMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
      
        //Bloco responsável pelo recebimento de dados do servidor
        try {
            socketClient = new Socket("localhost", (5050));
            
            fluxoDeEntrada = new DataInputStream(socketClient.getInputStream());
            fluxoDeSaida = new DataOutputStream(socketClient.getOutputStream());
            
            msgAserRecebida = "";
            while(!msgAserRecebida.equals("sair")){
                msgAserRecebida = fluxoDeEntrada.readUTF();
                switch (msgAserRecebida) {
                    case "sair":
                        //Alterando o background e o texto de alguns componentes
                        exibirMsg.setForeground(new java.awt.Color(0, 102, 102));
                        exibirMsg.setBackground(new java.awt.Color(0, 51, 51));
                        insiraTexto.setBackground(new java.awt.Color(0, 51, 51));
                        exibirMsg.setText("Conexão encerrada pelo servidor!");
                        //Interrompimento da comunicação
                        socketClient.close();
                        fluxoDeEntrada.close();
                        fluxoDeSaida.close();
                        break;
                    case "alerta":
                        ExecutarAudio alerta = new ExecutarAudio();
                        alerta.setTitle("O servidor está acenando para você !");
                        break;
                    default:
                        exibirMsg.setText(exibirMsg.getText()+msgAserRecebida);
                        break;
                }
            }
        } catch (IOException e) {
            System.out.println("Error em -----> "+e);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEnviar;
    private javax.swing.JLabel btn_alert;
    private javax.swing.JLabel emoji_heart;
    private javax.swing.JLabel emoji_smile;
    private static javax.swing.JTextArea exibirMsg;
    private static javax.swing.JTextField insiraTexto;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            new Client().setVisible(true);
        }
    }
}
